backend:
  name: github
  repo: igorch1955/igorch1955.github.io
  branch: main
  base_url: https://peaceful-daffodil-424726.netlify.app
  auth_endpoint: /.netlify/functions/auth

media_folder: "covers"
public_folder: "covers"

collections:
  - name: "papers"
    label: "Papers"
    files:
      - file: "works.json"
        label: "Publications data"
        name: "works"
        fields:
          - { label: "Papers", name: "papers", widget: "list", fields: [
              { label: "Kicker", name: "kicker", widget: "string" },
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Links", name: "links", widget: "list", fields: [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "URL", name: "url", widget: "string" }
                ]}
            ]}
          - { label: "Books", name: "books", widget: "list", fields: [
              { label: "Kicker", name: "kicker", widget: "string" },
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Cover image", name: "cover", widget: "image", required: false },
              { label: "Links", name: "links", widget: "list", fields: [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "URL", name: "url", widget: "string" }
                ]}
            ]}
